// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: protobuf/struct.proto

package protobuf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DataProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DataProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DataProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DataProtoMultiError, or nil
// if none found.
func (m *DataProto) ValidateAll() error {
	return m.validate(true)
}

func (m *DataProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.CreatedAt != nil {

		if all {
			switch v := interface{}(m.GetCreatedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DataProtoValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DataProtoValidationError{
						field:  "CreatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DataProtoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.UpdatedAt != nil {

		if all {
			switch v := interface{}(m.GetUpdatedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DataProtoValidationError{
						field:  "UpdatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DataProtoValidationError{
						field:  "UpdatedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DataProtoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DataProtoMultiError(errors)
	}

	return nil
}

// DataProtoMultiError is an error wrapping multiple validation errors returned
// by DataProto.ValidateAll() if the designated constraints aren't met.
type DataProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataProtoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataProtoMultiError) AllErrors() []error { return m }

// DataProtoValidationError is the validation error returned by
// DataProto.Validate if the designated constraints aren't met.
type DataProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataProtoValidationError) ErrorName() string { return "DataProtoValidationError" }

// Error satisfies the builtin error interface
func (e DataProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDataProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataProtoValidationError{}

// Validate checks the field values on PagingReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PagingReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PagingReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PagingReqMultiError, or nil
// if none found.
func (m *PagingReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PagingReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Query

	// no validation rules for OrderBy

	if m.Page != nil {
		// no validation rules for Page
	}

	if m.PageSize != nil {
		// no validation rules for PageSize
	}

	if m.Nopaging != nil {
		// no validation rules for Nopaging
	}

	if len(errors) > 0 {
		return PagingReqMultiError(errors)
	}

	return nil
}

// PagingReqMultiError is an error wrapping multiple validation errors returned
// by PagingReq.ValidateAll() if the designated constraints aren't met.
type PagingReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PagingReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PagingReqMultiError) AllErrors() []error { return m }

// PagingReqValidationError is the validation error returned by
// PagingReq.Validate if the designated constraints aren't met.
type PagingReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PagingReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PagingReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PagingReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PagingReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PagingReqValidationError) ErrorName() string { return "PagingReqValidationError" }

// Error satisfies the builtin error interface
func (e PagingReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPagingReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PagingReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PagingReqValidationError{}

// Validate checks the field values on PagingReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PagingReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PagingReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PagingReplyMultiError, or
// nil if none found.
func (m *PagingReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PagingReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PagingReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PagingReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PagingReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PagingReplyMultiError(errors)
	}

	return nil
}

// PagingReplyMultiError is an error wrapping multiple validation errors
// returned by PagingReply.ValidateAll() if the designated constraints aren't met.
type PagingReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PagingReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PagingReplyMultiError) AllErrors() []error { return m }

// PagingReplyValidationError is the validation error returned by
// PagingReply.Validate if the designated constraints aren't met.
type PagingReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PagingReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PagingReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PagingReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PagingReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PagingReplyValidationError) ErrorName() string { return "PagingReplyValidationError" }

// Error satisfies the builtin error interface
func (e PagingReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPagingReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PagingReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PagingReplyValidationError{}

// Validate checks the field values on ListReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListReplyMultiError, or nil
// if none found.
func (m *ListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListReplyMultiError(errors)
	}

	return nil
}

// ListReplyMultiError is an error wrapping multiple validation errors returned
// by ListReply.ValidateAll() if the designated constraints aren't met.
type ListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReplyMultiError) AllErrors() []error { return m }

// ListReplyValidationError is the validation error returned by
// ListReply.Validate if the designated constraints aren't met.
type ListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReplyValidationError) ErrorName() string { return "ListReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReplyValidationError{}

// Validate checks the field values on WebsocketProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WebsocketProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebsocketProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WebsocketProtoMultiError,
// or nil if none found.
func (m *WebsocketProto) ValidateAll() error {
	return m.validate(true)
}

func (m *WebsocketProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for Payload

	if len(errors) > 0 {
		return WebsocketProtoMultiError(errors)
	}

	return nil
}

// WebsocketProtoMultiError is an error wrapping multiple validation errors
// returned by WebsocketProto.ValidateAll() if the designated constraints
// aren't met.
type WebsocketProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebsocketProtoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebsocketProtoMultiError) AllErrors() []error { return m }

// WebsocketProtoValidationError is the validation error returned by
// WebsocketProto.Validate if the designated constraints aren't met.
type WebsocketProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebsocketProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebsocketProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebsocketProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebsocketProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebsocketProtoValidationError) ErrorName() string { return "WebsocketProtoValidationError" }

// Error satisfies the builtin error interface
func (e WebsocketProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebsocketProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebsocketProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebsocketProtoValidationError{}

// Validate checks the field values on WebsocketMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WebsocketMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebsocketMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WebsocketMessageMultiError, or nil if none found.
func (m *WebsocketMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *WebsocketMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Sender

	// no validation rules for Timestamp

	if len(errors) > 0 {
		return WebsocketMessageMultiError(errors)
	}

	return nil
}

// WebsocketMessageMultiError is an error wrapping multiple validation errors
// returned by WebsocketMessage.ValidateAll() if the designated constraints
// aren't met.
type WebsocketMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebsocketMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebsocketMessageMultiError) AllErrors() []error { return m }

// WebsocketMessageValidationError is the validation error returned by
// WebsocketMessage.Validate if the designated constraints aren't met.
type WebsocketMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebsocketMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebsocketMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebsocketMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebsocketMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebsocketMessageValidationError) ErrorName() string { return "WebsocketMessageValidationError" }

// Error satisfies the builtin error interface
func (e WebsocketMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebsocketMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebsocketMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebsocketMessageValidationError{}
